### ISSUE TITLE
when I fuzzer libjpeg-turbo module cjpeg use the default xml,some errors happen 

### ISSUE THREAD

**Issue by geekchenwu** [zodf0055980/Yuan-fuzz#3]
add 1154 in group 19
[*] run rarget = 412
[*] get b'skip'
[*] next group 1
[*] run target = 1106
[*] get b'next'
[*] find new path 1155 to 1171
add 1155 in group 25
add 1156 in group 25
add 1157 in group 25
add 1158 in group 25
add 1159 in group 25
add 1160 in group 25
add 1161 in group 25
add 1162 in group 25
add 1163 in group 25
add 1164 in group 25
add 1165 in group 25
add 1166 in group 25
add 1167 in group 25
add 1168 in group 25
add 1169 in group 1
add 1170 in group 25
add 1171 in group 25
[*] run rarget = 412
[*] get b'skip'
[*] group 0 is not interesting
[*] run target = 1106
[*] get b'skip'
[*] run target = 1108
[*] get b'next'
[*] find new path 1172 to 1187
Traceback (most recent call last):
  File "group_seed.py", line 208, in <module>
    out = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./afl-showmap', '-q', '-e', '-o', '/dev/stdout', '-m', 'none', '-t', '500', 'target/libjpeg-turbo/build/cjpeg', '-outfile', '/dev/null', 'fuzzer_out/cjpeg319/queue/id:001183,src:001108,op:havoc,rep:4']' returned non-zero exit status 1.

**Comment by zodf0055980** [comment]
Can you give me your python version and `queue/id:001183` file and `queue_info/queue/id:001183` file?

**Comment by geekchenwu** [comment]
Python 3.8.6

**Comment by geekchenwu** [comment]
[Uploading quen.zip…]()

**Comment by zodf0055980** [comment]
your upload zip is too huge, can just give me two files?

**Comment by zodf0055980** [comment]
I think this problem is about subprocess run showmap to get edge will crash when run crash process, but I can't reproduce this problem in my pc .....
I add an exception check in group_seed, I think it can solve this problem.

**Comment by zodf0055980** [comment]
please try it again, thanks.

**Comment by geekchenwu** [comment]
maybe it is the timeout number set，I change the “-t 500”to “-t 5000+”，so fix it

**Comment by zodf0055980** [comment]
But this will that group server cost a lot of time when having a lot of hang file.
I think add except is better.

**Comment by geekchenwu** [comment]
thanks
