### ISSUE TITLE
All the fuzzer die when fuzzing libxml2

### ISSUE THREAD

**Issue by CityOfLight77** [zodf0055980/Yuan-fuzz#4]
I run fuzzing campaign targetting libxml2 with group_seed on and few hours later all the fuzzer die.
I don't know what exactly happen as it doesn't display any error.
Is it mandatory to run group_seed or it's optional?

**Comment by zodf0055980** [comment]
Maybe you could checkout to this branch
https://github.com/zodf0055980/Yuan-fuzz/tree/Yuan-fuzz-1.0
This use original afl seed selection.

**Comment by CityOfLight77** [comment]
Okay I'll try.
When you fuzz libxml2 which selection strategy you used?

**Comment by zodf0055980** [comment]
I use our design seed selection with k-means (group_seed), and use -d mode to skips the deterministic stages.
Maybe you could give me the group_seed error and what command line you run.
It can help this fuzzer better, thanks.

**Comment by CityOfLight77** [comment]
I use `-d` on Master and `group_seed` selection, fuzzer still died

I compile libxml2 with this command
`CC=~/Yuan-fuzz/afl-clang-fast CXX=~/Yuan-fuzz/afl-clang-fast++ CFLAGS="-g -O0 -fsanitize=address,undefined,implicit-conversion,integer,nullability" CXXFLAGS="-g -O0 -fsanitize=address,undefined,implicit-conversion,integer,nullability" ./autogen.sh --disable-shared --without-debug --without-ftp --without-http --without-legacy --without-python`

I can't capture all error, but from what I saw all the corpus in group 0. Here is `group_seed` partial log

```sh
[*] run target = 13
[*] get b'skip'
[*] next group 0
[*] run target = 5
[*] get b'skip'
[*] next group 0
[*] run target = 4
[*] get b'skip'
[*] next group 0
[*] run target = 2
[*] get b'skip'
[*] next group 0
[*] run target = 2
[*] get b'skip'
[*] next group 0
[*] run target = 4
[*] get b'skip'
[*] next group 0
[*] run target = 5
[*] get b'skip'
[*] next group 0
[*] run target = 13
[*] get b'skip'
[*] next group 0
[*] run target = 13
[*] get b'skip'
[*] next group 0
[*] run target = 5
[*] get b'skip'
[*] next group 0
[*] run target = 4
[*] get b'skip'
[*] next group 0
[*] run target = 2
[*] get b'skip'
[*] next group 0
[*] run target = 2
[*] get b'skip'
[*] next group 0
[*] run target = 4
[*] get b'skip'
[*] next group 0
[*] run target = 5
[*] get b'notf'
[*] run target = 13
[*] get b'skip'
[*] next group 0
[*] run target = 13
[*] get b'skip'
[*] next group 0
[*] run target = 4
[*] get b'skip'
[*] next group 0
[*] run target = 2
[*] get b'skip'
[*] next group 0
[*] run target = 2
[*] get b'skip'
[*] next group 0
[*] run target = 4
[*] get b'notf'
Killed
```

**Comment by zodf0055980** [comment]
In group_seed, it use afl-shwmap to get seed path. 
In group_seed, is it all get `find a crash` when run afl-showmap? it means afl-showmap subprocess error.

**Comment by CityOfLight77** [comment]
> In group_seed, it use afl-shwmap to get seed path.
> In group_seed, is it all get `find a crash` when run afl-showmap? it means afl-showmap subprocess error.

In the first try yes it show `find a crash`. So if this is a subprocess error, are there any workaround on this?

**Comment by zodf0055980** [comment]
I try to build libxml2
```
export CC=~/Yuan-fuzz/afl-gcc
export CXX=~/Yuan-fuzz/afl-g++

CFLAGS="-g -O0 -fsanitize=address" CXXFLAGS="-g -O0 -fsanitize=address" ./autogen.sh --disable-shared --without-debug --without-ftp --without-http --without-legacy --without-python
```

run fuzzer:
```
python3 group_seed.py 6668

other terminal

./Yuan-fuzz -i ./testcases/others/xml -o ./xmlout -p 6668 -s ~/Yuan-fuzz/xml/libxml2/parameters.xml -b 15 -m none -- ~/libxml2/xmllint
```

group server:
```
[*] port = 6668
[*] dirpath = ./xmlout
[*] init_seed_count = 1
[*] kmeans_group = 20
['/home/yuan/libxml2/xmllint', './xmlout/queue/id:000000,orig:small_document.xml']
['/home/yuan/libxml2/xmllint', '--debugent', '--copy', '--recover', '--huge', '--nocompact', '--nowrap', '--postvalid', '--quiet', '--output', '/dev/null', '--insert', '--compress', '--xmlout', '--nodefdtd', '--noblanks', '--format', '--dropdtd', '--pretty', '1', '--nsclean', '--testIO', '--nocatalogs', '--auto', '--stream', '--sax1', '--sax', '--oldxml10', './xmlout/queue/id:000001,src:000000,op:arg1,pos:0,+cov']
.....
['/home/yuan/libxml2/xmllint', './xmlout/queue/id:000412,src:000000,op:havoc,rep:2']
[*] cluster_labels
[ 5 10 12  9  6  8  6  9 12 12  9  3 12  8  1  9  4 12 19  6  8 15  8  1
  1  9  6  9  1 15 17  8  4 15  6  6  1 19  6 17 17 12  3 19 12 19  9  4
  9  9 19  6  9  9 13  9 12 17  1 12  6  6  9 15  8  8  6  8  6  4  1  6
 17 19 19  6  8  9  1 17 12  3  1  8  8  3 17  6 13  4  6 17 19  4 15  8
  1  4 19 15  6  6 19  8  8 12 13  1  1  8 19  3 13  3  6 13 15  4 19  1
 15 19 13  3  3  1  3 19 15 19  8 19 19  3  3 15 13  4  1 13 19  3 12 19
  3  3  6  3  4  3 10 10 14 10 14 11 11 11 11  2 11 11  2  2  2  2  2  2
 18 18 18 18 18 14  7  7  7  0  7  0  7 14 14 14 10 10 11 16 11 16 11  2
  2  7  0  0 10  5 11 11  2 18  7  0  0  7 14 11 11  7 11 18  0 10 10 10
  5 11 18  2 18  5  7  7  0  0  0  0  0 14 10 10 16  5 14 14 10 11 10 11
 16 18 18  7  7  7  7  7  0 14 14 10 10 18  7  7 10 10 16 18  2 11 10 10
 10  2  2 10 14 18  7  2 10 11  7  0 10 14 10 14  2 10  5 16 10 18  0 18
  5 16 11 18 10  0 10 11 11 11 10 14 11 10 11  5 16 11  2 14  7 16 18  5
 16 10  5  2  0 11 18  2  2 14  7  0 10  0 10 14 10 11 11  7 10  0  2  2
  5 16 11  0  2 14 10 11  7 11  0 18 18 18 18 14  7 10  7  0  2 11  7  0
 11  5 10 14 14 14  0 11  7 11 10 10 10  7  0 10 10  2  5 18 10  5 10  0
 10  7 11  2  2  7  0 18 18 16 18  7 16  2  2 18  0  0 16 10  0  5 14 11
 14  7  0 16  5]
[*] show group
group 0 : 177, 179, 194, 195, 203, 204, 212, 224, 225, 226, 227, 228, 248, 275, 286, 293, 316, 323, 325, 333, 339, 346, 355, 359, 366, 374, 383, 390, 400, 401, 404, 410
group 1 : 14, 23, 24, 28, 36, 58, 70, 78, 82, 96, 107, 108, 119, 125, 138
group 2 : 159, 162, 163, 164, 165, 166, 167, 191, 192, 200, 219, 260, 265, 266, 271, 280, 306, 315, 319, 320, 334, 335, 340, 356, 377, 387, 388, 397, 398
group 3 : 11, 42, 81, 85, 111, 113, 123, 124, 126, 133, 134, 141, 144, 145, 147, 149
group 4 : 16, 32, 47, 69, 89, 93, 97, 117, 137, 148
group 5 : 197, 216, 221, 233, 282, 288, 303, 311, 314, 336, 361, 378, 381, 405, 412, 0
group 6 : 4, 6, 19, 26, 34, 35, 38, 51, 60, 61, 66, 68, 71, 75, 87, 90, 100, 101, 114, 146
group 7 : 174, 175, 176, 178, 180, 193, 202, 205, 209, 222, 223, 243, 244, 245, 246, 247, 254, 255, 270, 274, 308, 322, 331, 344, 352, 354, 358, 368, 373, 385, 389, 395, 409
group 8 : 5, 13, 20, 22, 31, 64, 65, 67, 76, 83, 84, 95, 103, 104, 109, 130
group 9 : 3, 7, 10, 15, 25, 27, 46, 48, 49, 52, 53, 55, 62, 77
group 10 : 1, 150, 151, 153, 184, 185, 196, 213, 214, 215, 230, 231, 236, 238, 251, 252, 256, 257, 262, 263, 264, 267, 272, 276, 278, 281, 284, 292, 294, 298, 301, 313, 324, 326, 328, 332, 342, 353, 362, 370, 371, 372, 375, 376, 380, 382, 384, 403
group 11 : 155, 156, 157, 158, 160, 161, 186, 188, 190, 198, 199, 207, 208, 210, 217, 237, 239, 261, 273, 290, 295, 296, 297, 300, 302, 305, 317, 329, 330, 338, 343, 345, 357, 360, 367, 369, 386, 407
group 12 : 2, 8, 9, 12, 17, 41, 44, 56, 59, 80, 105, 142
group 13 : 54, 88, 106, 112, 115, 122, 136, 139
group 14 : 152, 154, 173, 181, 182, 183, 206, 229, 234, 235, 249, 250, 268, 277, 279, 299, 307, 321, 327, 341, 351, 363, 364, 365, 406, 408
group 15 : 21, 29, 33, 63, 94, 99, 116, 120, 128, 135
group 16 : 187, 189, 232, 240, 258, 283, 289, 304, 309, 312, 337, 393, 396, 402, 411
group 17 : 30, 39, 40, 57, 72, 79, 86, 91
group 18 : 168, 169, 170, 171, 172, 201, 211, 218, 220, 241, 242, 253, 259, 269, 285, 287, 291, 310, 318, 347, 348, 349, 350, 379, 391, 392, 394, 399
group 19 : 18, 37, 43, 45, 50, 73, 74, 92, 98, 102, 110, 118, 121, 127, 129, 131, 132, 140, 143
[*] run rarget = 177

```

Can you help to run `./afl-showmap -q -e -o /dev/stdout -m none -t 500 [argv group server show]` , and give me your result?

**Comment by zodf0055980** [comment]
for example.
```
./afl-showmap -q -e -o /dev/stdout -m none -t 500 /home/yuan/libxml2/xmllint ./xmlout/queue/id:000000,orig:small_document.xml
```
And it will show a lot of edge numbers.
```
000080:1
000124:1
000165:1
000251:1
000393:1
...
065057:1
065131:1
065157:1
065208:1
065323:1
065499:1
065524:1
065534:1
```

**Comment by CityOfLight77** [comment]
> I try to build libxml2
> 
> ```
> export CC=~/Yuan-fuzz/afl-gcc
> export CXX=~/Yuan-fuzz/afl-g++
> 
> CFLAGS="-g -O0 -fsanitize=address" CXXFLAGS="-g -O0 -fsanitize=address" ./autogen.sh --disable-shared --without-debug --without-ftp --without-http --without-legacy --without-python
> ```
> 
> run fuzzer:
> 
> ```
> python3 group_seed.py 6668
> 
> other terminal
> 
> ./Yuan-fuzz -i ./testcases/others/xml -o ./xmlout -p 6668 -s ~/Yuan-fuzz/xml/libxml2/parameters.xml -b 15 -m none -- ~/libxml2/xmllint
> ```
> 
> group server:
> 
> ```
> [*] port = 6668
> [*] dirpath = ./xmlout
> [*] init_seed_count = 1
> [*] kmeans_group = 20
> ['/home/yuan/libxml2/xmllint', './xmlout/queue/id:000000,orig:small_document.xml']
> ['/home/yuan/libxml2/xmllint', '--debugent', '--copy', '--recover', '--huge', '--nocompact', '--nowrap', '--postvalid', '--quiet', '--output', '/dev/null', '--insert', '--compress', '--xmlout', '--nodefdtd', '--noblanks', '--format', '--dropdtd', '--pretty', '1', '--nsclean', '--testIO', '--nocatalogs', '--auto', '--stream', '--sax1', '--sax', '--oldxml10', './xmlout/queue/id:000001,src:000000,op:arg1,pos:0,+cov']
> .....
> ['/home/yuan/libxml2/xmllint', './xmlout/queue/id:000412,src:000000,op:havoc,rep:2']
> [*] cluster_labels
> [ 5 10 12  9  6  8  6  9 12 12  9  3 12  8  1  9  4 12 19  6  8 15  8  1
>   1  9  6  9  1 15 17  8  4 15  6  6  1 19  6 17 17 12  3 19 12 19  9  4
>   9  9 19  6  9  9 13  9 12 17  1 12  6  6  9 15  8  8  6  8  6  4  1  6
>  17 19 19  6  8  9  1 17 12  3  1  8  8  3 17  6 13  4  6 17 19  4 15  8
>   1  4 19 15  6  6 19  8  8 12 13  1  1  8 19  3 13  3  6 13 15  4 19  1
>  15 19 13  3  3  1  3 19 15 19  8 19 19  3  3 15 13  4  1 13 19  3 12 19
>   3  3  6  3  4  3 10 10 14 10 14 11 11 11 11  2 11 11  2  2  2  2  2  2
>  18 18 18 18 18 14  7  7  7  0  7  0  7 14 14 14 10 10 11 16 11 16 11  2
>   2  7  0  0 10  5 11 11  2 18  7  0  0  7 14 11 11  7 11 18  0 10 10 10
>   5 11 18  2 18  5  7  7  0  0  0  0  0 14 10 10 16  5 14 14 10 11 10 11
>  16 18 18  7  7  7  7  7  0 14 14 10 10 18  7  7 10 10 16 18  2 11 10 10
>  10  2  2 10 14 18  7  2 10 11  7  0 10 14 10 14  2 10  5 16 10 18  0 18
>   5 16 11 18 10  0 10 11 11 11 10 14 11 10 11  5 16 11  2 14  7 16 18  5
>  16 10  5  2  0 11 18  2  2 14  7  0 10  0 10 14 10 11 11  7 10  0  2  2
>   5 16 11  0  2 14 10 11  7 11  0 18 18 18 18 14  7 10  7  0  2 11  7  0
>  11  5 10 14 14 14  0 11  7 11 10 10 10  7  0 10 10  2  5 18 10  5 10  0
>  10  7 11  2  2  7  0 18 18 16 18  7 16  2  2 18  0  0 16 10  0  5 14 11
>  14  7  0 16  5]
> [*] show group
> group 0 : 177, 179, 194, 195, 203, 204, 212, 224, 225, 226, 227, 228, 248, 275, 286, 293, 316, 323, 325, 333, 339, 346, 355, 359, 366, 374, 383, 390, 400, 401, 404, 410
> group 1 : 14, 23, 24, 28, 36, 58, 70, 78, 82, 96, 107, 108, 119, 125, 138
> group 2 : 159, 162, 163, 164, 165, 166, 167, 191, 192, 200, 219, 260, 265, 266, 271, 280, 306, 315, 319, 320, 334, 335, 340, 356, 377, 387, 388, 397, 398
> group 3 : 11, 42, 81, 85, 111, 113, 123, 124, 126, 133, 134, 141, 144, 145, 147, 149
> group 4 : 16, 32, 47, 69, 89, 93, 97, 117, 137, 148
> group 5 : 197, 216, 221, 233, 282, 288, 303, 311, 314, 336, 361, 378, 381, 405, 412, 0
> group 6 : 4, 6, 19, 26, 34, 35, 38, 51, 60, 61, 66, 68, 71, 75, 87, 90, 100, 101, 114, 146
> group 7 : 174, 175, 176, 178, 180, 193, 202, 205, 209, 222, 223, 243, 244, 245, 246, 247, 254, 255, 270, 274, 308, 322, 331, 344, 352, 354, 358, 368, 373, 385, 389, 395, 409
> group 8 : 5, 13, 20, 22, 31, 64, 65, 67, 76, 83, 84, 95, 103, 104, 109, 130
> group 9 : 3, 7, 10, 15, 25, 27, 46, 48, 49, 52, 53, 55, 62, 77
> group 10 : 1, 150, 151, 153, 184, 185, 196, 213, 214, 215, 230, 231, 236, 238, 251, 252, 256, 257, 262, 263, 264, 267, 272, 276, 278, 281, 284, 292, 294, 298, 301, 313, 324, 326, 328, 332, 342, 353, 362, 370, 371, 372, 375, 376, 380, 382, 384, 403
> group 11 : 155, 156, 157, 158, 160, 161, 186, 188, 190, 198, 199, 207, 208, 210, 217, 237, 239, 261, 273, 290, 295, 296, 297, 300, 302, 305, 317, 329, 330, 338, 343, 345, 357, 360, 367, 369, 386, 407
> group 12 : 2, 8, 9, 12, 17, 41, 44, 56, 59, 80, 105, 142
> group 13 : 54, 88, 106, 112, 115, 122, 136, 139
> group 14 : 152, 154, 173, 181, 182, 183, 206, 229, 234, 235, 249, 250, 268, 277, 279, 299, 307, 321, 327, 341, 351, 363, 364, 365, 406, 408
> group 15 : 21, 29, 33, 63, 94, 99, 116, 120, 128, 135
> group 16 : 187, 189, 232, 240, 258, 283, 289, 304, 309, 312, 337, 393, 396, 402, 411
> group 17 : 30, 39, 40, 57, 72, 79, 86, 91
> group 18 : 168, 169, 170, 171, 172, 201, 211, 218, 220, 241, 242, 253, 259, 269, 285, 287, 291, 310, 318, 347, 348, 349, 350, 379, 391, 392, 394, 399
> group 19 : 18, 37, 43, 45, 50, 73, 74, 92, 98, 102, 110, 118, 121, 127, 129, 131, 132, 140, 143
> [*] run rarget = 177
> ```
> 
> Can you help to run `./afl-showmap -q -e -o /dev/stdout -m none -t 500 [argv group server show]` , and give me your result?

It works. Seems the problem is I was running yuan-fuzz with master and slave. Running single core doesn't matter. I think you should put this on readme
What does `-b` do? I'm skipping it

**Comment by zodf0055980** [comment]
-b is bind fuzzer in specified cpu core,.
I not implement master and slave, so maybe it will not work. 
I will add this in README.

Thanks.

**Comment by CityOfLight77** [comment]
Thanks for helping me

**Comment by CityOfLight77** [comment]
Another problem: I'm fuzzing on single core with `-r` and suddenly `group_seed` killed. Surprisingly, the fuzzer still on.
What will happen if the `group_seed` killed? It use AFL seed selection?

Here is the log

```sh
['/home/cityoflight77/libxml2/xmllint', '--noout', '--path', '--load-trace', '--nocompact', '--nowrap', '--valid', '--quiet', '--timing', '--insert', '--compress', '--html', '--xmlout', '--push', '--pushsmall', '--memory', '--noblanks', '--nocdata', '--format', '--exc-c14n', '--nsclean', '--nocatalogs', '--dtdattr', '--walker', '--sax1', '--oldxml10', 'output/queue/id:005348,src:000321,op:havoc,rep:64']
['/home/cityoflight77/libxml2/xmllint', '--noout', '--path', '--load-trace', '--nocompact', '--nowrap', '--valid', '--quiet', '--timing', '--insert', '--compress', '--html', '--xmlout', '--push', '--pushsmall', '--memory', '--noblanks', '--nocdata', '--format', '--exc-c14n', '--nsclean', '--nocatalogs', '--dtdattr', '--walker', '--sax1', '--oldxml10', 'output/queue/id:005349,src:000321,op:havoc,rep:64']
['/home/cityoflight77/libxml2/xmllint', '--noout', '--path', '--load-trace', '--nocompact', '--nowrap', '--valid', '--quiet', '--timing', '--insert', '--compress', '--html', '--xmlout', '--push', '--pushsmall', '--memory', '--noblanks', '--nocdata', '--format', '--exc-c14n', '--nsclean', '--nocatalogs', '--dtdattr', '--walker', '--sax1', '--oldxml10', 'output/queue/id:005350,src:000321,op:havoc,rep:32,+cov']
Killed
```

**Comment by zodf0055980** [comment]
`-r` will generate random command-line argv,Maybe somethings caused python error. 
If group_seed killed, the fuzzer will hangs and keep fuzz seed 0, I don't implement about group_seed killed, sorry.
Maybe I will add this part later, thanks.

**Comment by zodf0055980** [comment]
I modify `-p` option, without `-p` option will use original AFL linear seed selection.
But in my experiment，use our seed selection will more better.
